version: '3.4'

services:
# KriniteWebShop.ProductCatalog.API
  krinitewebshop.catalog.api:
    image: ${DOCKER_REGISTRY-}krinitewebshopcatalogapi
    build:
      context: ../Services/
      dockerfile: Catalog/KriniteWebShop.Catalog.API/Dockerfile
    networks:
      static-network:
        ipv4_address: 172.26.100.1

  productdb.mssql:
    image: mcr.microsoft.com/mssql/server:latest
    networks:
      static-network:
        ipv4_address: 172.26.100.2

# KriniteWebShop.ProductCatalog.NoSQL.API
  krinitewebshop.catalog.nosql.api:
    image: ${DOCKER_REGISTRY-}krinitewebshopcatalognosqlapi
    build:
      context: ../Services/
      dockerfile: Catalog/KriniteWebShop.Catalog.NoSQL.API/Dockerfile
    networks:
      static-network:
        ipv4_address: 172.26.102.1
        
  productdb.mongo:
    image: mongo
    networks:
      static-network:
        ipv4_address: 172.26.102.2

# KriniteWebShop.ProductCart.API
  krinitewebshop.cart.api:
    image: ${DOCKER_REGISTRY-}krinitewebshopcartapi
    build:
      context: ../Services/
      dockerfile: Cart/KriniteWebShop.Cart.API/Dockerfile
    networks:
      static-network:
        ipv4_address: 172.26.104.1
        
  cartdb.redis:
    image: redis
    networks:
      static-network:
        ipv4_address: 172.26.104.2


# KriniteWebShop.ProductCoupon.API
  krinitewebshop.coupon.api:
    image: ${DOCKER_REGISTRY-}krinitewebshopcouponapi
    build:
      context: ../Services/
      dockerfile: Coupon/KriniteWebShop.Coupon.API/Dockerfile
    networks:
      static-network:
        ipv4_address: 172.26.106.1
  
  krinitewebshop.coupon.grpc:
    image: ${DOCKER_REGISTRY-}krinitewebshopcoupongrpc
    build:
      context: ../Services/
      dockerfile: Coupon/KriniteWebShop.Coupon.gRPC/Dockerfile
    networks:
      static-network:
        ipv4_address: 172.26.106.2
        
  coupondb.postgresql:
    image: postgres
    networks:
      static-network:
        ipv4_address: 172.26.106.3

# KriniteWebShop.ProductOrder.API 
  krinitewebshop.order.api:
    image: ${DOCKER_REGISTRY-}krinitewebshoporderapi
    build:
      context: ../Services/
      dockerfile: Order/KriniteWebShop.Order.API/Dockerfile
    networks:
      static-network:
        ipv4_address: 172.26.108.1

  orderdb.mssql:
    image: mcr.microsoft.com/mssql/server:latest
    networks:
      static-network:
        ipv4_address: 172.26.108.2

# KriniteWebShop.PurchaseAggregator
  krinitewebshop.purchaseaggregator:
    image: ${DOCKER_REGISTRY-}krinitewebshoppurchaseaggregator
    build:
      context: ../
      dockerfile: KriniteWebShop.PurchaseAggregator/Dockerfile
    networks:
      static-network:
        ipv4_address: 172.26.110.1

# KriniteWebShop.GatewayAPI
  krinitewebshop.gatewayapi:
    image: ${DOCKER_REGISTRY-}krinitewebshopgatewayapi
    build:
      context: ../
      dockerfile: KriniteWebShop.GatewayAPI/Dockerfile
    networks:
      static-network:
        ipv4_address: 172.26.112.1

# KriniteWebShop.WebClient
  krinitewebshop.webui.razorpages:
    image: ${DOCKER_REGISTRY-}krinitewebshopwebuirazorpages
    build:
      context: ../WebUI/
      dockerfile: KriniteWebShop.WebUI.RazorPages/Dockerfile
    networks:
      static-network:
        ipv4_address: 172.26.120.1

# KriniteWebShop.WebBlazorClient
  krinitewebshop.webui.blazor:
    image: ${DOCKER_REGISTRY-}krinitewebshopwebuiblazor
    build:
      context: ../WebUI/
      dockerfile: KriniteWebShop.WebUI.Blazor/Dockerfile
    networks:
      static-network:
        ipv4_address: 172.26.122.1

# Tools
  portainer:
    image: portainer/portainer-ce:latest
    networks:
      static-network:
        ipv4_address: 172.26.190.1

  mongodbclient:
    image: mongoclient/mongoclient
    networks:
      static-network:
        ipv4_address: 172.26.191.1
      
  pgadmin4:
    image: dpage/pgadmin4
    networks:
      static-network:
        ipv4_address: 172.26.192.2

  rabbitmq:
    image: rabbitmq:3-management-alpine
    networks:
      static-network:
        ipv4_address: 172.26.193.1

networks:
  static-network:
    ipam:
      config:
        - subnet: 172.26.0.0/16

volumes:
  portainer_data: