version: '3.4'

services:
  krinitewebshop.productcatalog.api:
    image: ${DOCKER_REGISTRY-}krinitewebshopproductcatalogapi
    build:
      context: .
      dockerfile: KriniteWebShop.ProductCatalog.API/Dockerfile
    networks:
      static-network:
        ipv4_address: 172.26.155.1

  productsdb:
    image: mcr.microsoft.com/mssql/server:latest
    networks:
      static-network:
        ipv4_address: 172.26.155.2

  krinitewebshop.productcatalog.nosql.api:
    image: ${DOCKER_REGISTRY-}krinitewebshopproductcatalognosqlapi
    build:
      context: .
      dockerfile: KriniteWebShop.ProductCatalog.NoSQL.API/Dockerfile
    networks:
      static-network:
        ipv4_address: 172.26.156.1

  productsdbmongo:
    image: mongo
    networks:
      static-network:
        ipv4_address: 172.26.156.2

networks:
  static-network:
    ipam:
      config:
        - subnet: 172.26.0.0/16