version: '3.4'

services:
  krinitewebshop.productcatalog.api:
    image: ${DOCKER_REGISTRY-}krinitewebshopproductcatalogapi
    build:
      context: .
      dockerfile: KriniteWebShop.ProductCatalog.API/Dockerfile
    networks:
      static-network:
        ipv4_address: 172.26.150.1

  productdb:
    image: mcr.microsoft.com/mssql/server:latest
    networks:
      static-network:
        ipv4_address: 172.26.150.2



  krinitewebshop.productcatalog.nosql.api:
    image: ${DOCKER_REGISTRY-}krinitewebshopproductcatalognosqlapi
    build:
      context: .
      dockerfile: KriniteWebShop.ProductCatalog.NoSQL.API/Dockerfile
    networks:
      static-network:
        ipv4_address: 172.26.151.1
        
  productdbmongo:
    image: mongo
    networks:
      static-network:
        ipv4_address: 172.26.151.2

  mongodbclient:
    image: mongoclient/mongoclient
    networks:
      static-network:
        ipv4_address: 172.26.151.3



  krinitewebshop.productcart.api:
    image: ${DOCKER_REGISTRY-}krinitewebshopproductcartapi
    build:
      context: .
      dockerfile: KriniteWebShop.ProductCart.API/Dockerfile
    networks:
      static-network:
        ipv4_address: 172.26.152.1
        
  cartdb:
    image: redis
    networks:
      static-network:
        ipv4_address: 172.26.152.2



  krinitewebshop.productcoupon.grpc:
    image: ${DOCKER_REGISTRY-}krinitewebshopproductcoupongrpc
    build:
      context: .
      dockerfile: KriniteWebShop.ProductCoupon.gRPC/Dockerfile
    networks:
      static-network:
        ipv4_address: 172.26.154.1
        
  coupondb:
    image: postgres
    networks:
      static-network:
        ipv4_address: 172.26.154.2
        
  pgadmin4:
    image: dpage/pgadmin4
    networks:
      static-network:
        ipv4_address: 172.26.154.3



networks:
  static-network:
    ipam:
      config:
        - subnet: 172.26.0.0/16