version: '3.4'

services:
  krinitewebshop.productcatalog.api:
    container_name: KriniteWebShop.ProductCatalog.API
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings:ProductsConnection=Server=172.26.155.2,1433;Database=Products;User ID=sa;Password=NotAll0wedForPublic;MultipleActiveResultSets=true;TrustServerCertificate=True
    ports:
      - "5820:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    depends_on:
      - productsdb

  productsdb:
    container_name: KriniteWebShop.ProductCatalog.API.MsSQL
    environment:
      SA_PASSWORD: "NotAll0wedForPublic"
      ACCEPT_EULA: "Y"
    restart: always
    ports:
      - "8720:1433"

  krinitewebshop.productcatalog.nosql.api:
    container_name: KriniteWebShop.ProductCatalog.NoSQL.API
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:80
      - DatabaseSettings:ConnectionString=mongodb://172.26.156.2:27017
    ports:
      - "5821:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    depends_on:
      - productsdbmongo

  productsdbmongo:
    container_name: KriniteWebShop.ProductCatalog.NoSQL.API.Mongo
    restart: always
    ports:
        - "27001:27017"
        
  mongodbclient:
    container_name: KriniteWebShop.ProductCatalog.NoSQL.API.MongoClient
    restart: always
    ports:
        - "3001:3000"